### ISSUE TITLE
Hardware Finish/Color

### ISSUE THREAD

**Issue by MilosKrumpolcCZ** [benov84/homebridge-dummy-lock-homekey#3]
What are the other values for the HardwareFinish/Color setting? For example, black or gold finish

**Comment by benov84** [comment]
I don't know unfortunately. You can check here [https://github.com/kupa22/apple-homekey](https://github.com/kupa22/apple-homekey), but I haven't tried to figure them myself. If you find out, please write back, so I can update the readme, thanks

**Comment by MilosKrumpolcCZ** [comment]
> I don't know unfortunately. You can check here https://github.com/kupa22/apple-homekey, but I haven't tried to figure them myself. If you find out, please write back, so I can update the readme, thanks

And where did you get this value: AQT///8A for card color choice? I went through https://github.com/kupa22/apple-homekey but I didn't come across the same value anywhere

**Comment by crystall1nedev** [comment]
The default value of `AQT///8A` is `0x1040FFFFFF00` when converted to hex. This is invalid, so HomeKit defaults to the Tan color.

Here’s a table of proper values and their hex conversions:
| Hex | Base64 | Color |
| --- | --- | --- |
| `0104CED5DA00` | `AQTO1doA` | Tan |
| `0104AAD6EC00` | `AQSq1uwA` | Gold |
| `0104E3E3E300` | `AQTj4+MA` | Silver |
| `010400000000` | `AQQAAAAA` | Black |

I just tested, these values should all work perfectly.
